### ISSUE TITLE
Project update: Put workplan and ToDo list in git project for transparency

### ISSUE THREAD

**Issue by om3ga-solutions** [OM3GA-SOLUTIONS-d-o-o/daktilograf-STT#3]
Put every task from work-plan to [Issues](https://github.com/OM3GA-SOLUTIONS-d-o-o/daktilograf-STT/issues) for transparency

Put tasks from To-Do list in [issues](https://github.com/OM3GA-SOLUTIONS-d-o-o/daktilograf-STT/issues) for easy tracking

**Comment by snj1988** [comment]
translate documentation into local language

**Comment by snj1988** [comment]
Translate documentation into local language
